[workspace]
channels = ["conda-forge"]
name = "plotly-dash-demo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "python 6_multipage.py"

[dependencies]
jupyterlab = ">=4.4.10,<5"
dash = ">=3.2.0,<4"
plotly = ">=6.4.0,<7"
numpy = ">=2.3.4,<3"
pandas = ">=2.3.3,<3"
dash-bootstrap-components = ">=2.0.4,<3"
